version: "2.1"

services:
  database:
    image: "mysql"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Red-Is-Blue"
      MYSQL_DATABASE: "redmine"
      MYSQL_USER: "redmine"
      MYSQL_PASSWORD: "redm1n3"
    networks:
      private:
        ipv4_address: 172.68.0.15
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redmine:
    image: "redmine"
    tty: true
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:3000:3000"
    environment:
      DB_HOST: "172.68.0.15"
    networks:
      private:
        ipv4_address: 172.68.0.10
    depends_on:
      database:
            condition: service_healthy
    volumes:
      - ./nginx_logs:/var/log/nginx

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 172.68.0.0/16
